root: ./

redirects:  
    security: contributors/contributing/security/README.md
    guides/developer/quick-start: development-docs.md
    docs.rocket.chat/apps-development/getting-started: development-docs.md 
    
