root: ./

redirects:  
    security: contributors/contributing/security/README.md
    guides/developer/quick-start: development-docs.md
    docs/developer-guides/rest-api/: development-docs.md 
    docs/guides/developer/mobile-apps/whitelabeling-mobile-apps: development-docs.md 
    docs/apps-development/: development-docs.md
    docs/guides/bots-guides/: development-docs.md
    
