redirects:  
    security: contributors/contributing/security/README.md
    guides/developer/quick-start: guides/developer/README.md
  docs.rocket.chat/api/rest-api/methods/chat: developer-docs/api/rest-api/README.md
