root: ./

redirects:  
    security: contributors/contributing/security/README.md
    guides/developer/quick-start: development-docs.md
    docs/api/: development-docs.md 
    docs/api/rest-api/: development-docs.md 
    apps-development/getting-started#start-developing: development-docs.md 
    
